'use client';

import { useMemo, useState } from 'react';

type Day = 'Segunda' | 'Terca' | 'Quarta' | 'Quinta' | 'Sexta';
const CAPACITY = 360;
const HOURS = Array.from({ length: 16 }, (_, index) => index + 6);
const DAYS: { value: Day; label: string }[] = [
  { value: 'Segunda', label: 'Segunda-feira' }, { value: 'Terca', label: 'Terça-feira' },
  { value: 'Quarta', label: 'Quarta-feira' }, { value: 'Quinta', label: 'Quinta-feira' },
  { value: 'Sexta', label: 'Sexta-feira' },
];

const forecast: Record<Day, { piso: number[]; teto: number[] }> = {
  Segunda: { piso: [0,81,205,261,254,254,243,152,122,116,59,25,0,0,0,0], teto: [0,100,254,326,322,326,328,244,225,227,175,148,121,121,110,74] },
  Terca: { piso: [0,94,226,241,238,236,234,163,148,152,108,62,0,0,0,0], teto: [0,119,288,311,315,320,332,272,272,288,250,212,149,117,130,107] },
  Quarta: { piso: [0,79,202,254,250,250,243,176,138,131,78,59,25,4,0,0], teto: [0,97,249,316,315,322,323,267,240,240,195,186,157,145,136,104] },
  Quinta: { piso: [0,85,226,260,255,249,245,193,161,145,96,60,24,0,0,0], teto: [0,104,280,328,326,325,332,291,269,260,218,190,161,144,128,105] },
  Sexta: { piso: [0,51,141,213,262,269,262,164,116,93,33,0,0,0,0,0], teto: [0,59,165,249,311,325,325,233,192,172,113,45,23,10,7,3] },
};
const bike: Record<Day, number[]> = {
  Segunda: [10,42,59,155,180,197,201,173,165,161,149,100,79,51,24,12], Terca: [14,44,73,90,107,110,106,124,128,113,88,71,47,33,19,8],
  Quarta: [6,22,55,101,124,123,125,102,77,82,76,60,53,27,17,6], Quinta: [7,29,74,114,126,122,118,100,102,98,104,74,57,39,19,8],
  Sexta: [8,37,65,131,164,146,148,131,107,99,72,46,30,13,6,3],
};
const neighborhoods = [
  { name: 'Barra da Tijuca', students: 300, cars: 52.0, groups: 17, color: '#efb35b' }, { name: 'Copacabana', students: 151, cars: 26.2, groups: 8, color: '#6c9df8' },
  { name: 'Leblon', students: 138, cars: 23.9, groups: 7, color: '#72c6a7' }, { name: 'Botafogo', students: 118, cars: 20.5, groups: 6, color: '#b18cff' },
  { name: 'Gávea', students: 107, cars: 18.6, groups: 6, color: '#f18482' }, { name: 'Ipanema', students: 96, cars: 16.7, groups: 5, color: '#80c6dd' },
];
const dayLabel = (day: Day) => DAYS.find((item) => item.value === day)?.label ?? day;
function statusFor(pct: number) { if (pct >= 90) return { label: 'Risco alto', tone: 'danger', copy: 'Pouca margem para chegar sem plano B.' }; if (pct >= 70) return { label: 'Atenção', tone: 'warning', copy: 'A ocupação pode mudar rápido neste período.' }; return { label: 'Boa margem', tone: 'good', copy: 'Há espaço projetado, mas a previsão é uma faixa.' }; }

export default function Home() {
  const [day, setDay] = useState<Day>('Terca'); const [hour, setHour] = useState(9); const [mode, setMode] = useState<'carro' | 'bike'>('carro');
  const [neighborhood, setNeighborhood] = useState('Barra da Tijuca'); const [showDetails, setShowDetails] = useState(false);
  const selected = useMemo(() => { const index = Math.max(0, Math.min(HOURS.length - 1, hour - 6)); const data = forecast[day]; const piso = data.piso[index]; const teto = data.teto[index]; return { index, piso, teto, pct: Math.round(teto / CAPACITY * 100), status: statusFor(Math.round(teto / CAPACITY * 100)) }; }, [day, hour]);
  const selectedNeighborhood = neighborhoods.find((item) => item.name === neighborhood) ?? neighborhoods[0]; const chartMax = mode === 'carro' ? CAPACITY : 420; const chartValues = mode === 'carro' ? forecast[day].teto : bike[day];
  const nextHours = HOURS.slice(selected.index, selected.index + 4); const recommendation = selected.pct >= 90 ? 'Considere carona ou transporte alternativo.' : selected.pct >= 70 ? 'Se puder, combine carona e evite chegar sozinho.' : 'O horário tem margem projetada para o rotativo.';

  return <main className="site-shell">
    <nav className="topbar"><a className="brand" href="#inicio" aria-label="Vaga Certa início"><span className="brand-mark">V</span><span>Vaga <em>Certa</em></span></a><div className="nav-links"><a href="#previsao">Previsão</a><a href="#caronas">Caronas</a><a href="#metodo">Como funciona</a></div><span className="data-pill"><span className="pulse" /> Base histórica · 5 dias</span></nav>

    <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">Mobilidade para a comunidade PUC-Rio</p><h1>Antes de sair, saiba<br /><span>se vale ir de carro.</span></h1><p className="hero-lede">Uma leitura simples da ocupação histórica do rotativo e alternativas de carona para você tomar uma decisão melhor — sem adivinhar.</p><div className="hero-actions"><a className="primary-button" href="#previsao">Ver previsão <span>↓</span></a><a className="text-button" href="#caronas">Encontrar carona <span>→</span></a></div></div><div className="hero-card"><div className="hero-card-top"><span>Próximo pico projetado</span><span className="mini-dot" /></div><div className="hero-number">9<span>h</span></div><p>terça-feira · chegada de alunos</p><div className="mini-bars" aria-label="Curva de ocupação das 6h às 13h">{[24,45,71,84,87,89,76,58].map((value, index) => <i key={index} style={{ height: `${value}%` }} />)}</div><div className="hero-card-foot"><span>Ocupação no pico</span><strong>87–92%</strong></div></div></section>

    <section className="decision-section" id="previsao"><div className="section-heading"><div><p className="eyebrow">01 · decisão rápida</p><h2>Vou encontrar vaga?</h2></div><p className="section-note">Selecione seu cenário. A projeção usa o histórico oficial e mantém a incerteza visível.</p></div>
      <div className="controls-card"><label>Quero chegar na <select value={hour} onChange={(event) => setHour(Number(event.target.value))}>{Array.from({ length: 13 }, (_, index) => index + 7).map((value) => <option key={value} value={value}>{value}h</option>)}</select></label><label>em <select value={day} onChange={(event) => setDay(event.target.value as Day)}>{DAYS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><div className="mode-toggle" role="group" aria-label="Modal de transporte"><button className={mode === 'carro' ? 'active' : ''} onClick={() => setMode('carro')}>🚗 Carro</button><button className={mode === 'bike' ? 'active' : ''} onClick={() => setMode('bike')}>🚲 Bike</button></div></div>
      {mode === 'carro' ? <div className="forecast-grid"><div className="forecast-main"><div className="forecast-label"><span>Ocupação estimada às {hour}h</span><span className={`status ${selected.status.tone}`}>{selected.status.label}</span></div><div className="forecast-range"><strong>{selected.piso}–{selected.teto}</strong><span> carros<br />de {CAPACITY} vagas</span></div><p className="muted">Faixa histórica para {dayLabel(day)}. O teto é o cenário conservador.</p><div className="capacity-track"><span style={{ width: `${Math.min(100, selected.teto / CAPACITY * 100)}%` }} /></div><div className="track-labels"><span>0</span><span>180</span><span>360 vagas</span></div><div className="insight"><span className="insight-icon">✦</span><div><strong>{recommendation}</strong><p>{selected.status.copy} A capacidade do rotativo é 360 vagas.</p></div></div></div><div className="metrics-stack"><div className="metric-card"><span>Vagas livres projetadas</span><strong>{Math.max(0, CAPACITY - selected.teto)}–{Math.max(0, CAPACITY - selected.piso)}</strong><small>cenário conservador → amplo</small></div><div className="metric-card accent"><span>Próximas horas</span><div className="next-hours">{nextHours.map((value, index) => { const data = forecast[day]; const valuePct = Math.round(data.teto[selected.index + index] / CAPACITY * 100); return <div key={value}><i style={{ height: `${Math.max(8, valuePct)}%` }} /><b>{value}h</b></div>; })}</div><small>Tendência de ocupação</small></div></div></div> : <div className="bike-card"><div><p className="eyebrow">Bicicletário · {dayLabel(day)}</p><div className="bike-number">{bike[day][selected.index]} <span>bikes projetadas às {hour}h</span></div><p className="muted">A capacidade instalada não está disponível no dataset. Por isso, mostramos volume absoluto — nunca um percentual inventado.</p></div><div className="bike-warning"><span>!</span><div><strong>Falta o denominador</strong><p>O máximo observado foi 396 bicicletas. Isso é um piso de uso, não a capacidade do bicicletário.</p></div></div></div>}
      <div className="chart-card"><div className="chart-head"><div><p className="eyebrow">Curva do dia</p><h3>{mode === 'carro' ? 'Ocupação do rotativo' : 'Bicicletas no bicicletário'}</h3></div><button className="details-button" onClick={() => setShowDetails(!showDetails)}>{showDetails ? 'Ocultar detalhes' : 'Ver detalhes'} <span>{showDetails ? '↑' : '↓'}</span></button></div><div className="chart-area" aria-label={`Curva de ${mode === 'carro' ? 'ocupação do carro' : 'bicicletas'} para ${dayLabel(day)}`}><div className="chart-y"><span>{chartMax}</span><span>{Math.round(chartMax * .5)}</span><span>0</span></div><div className="bars">{chartValues.map((value, index) => <div className={`bar-wrap ${index + 6 === hour ? 'selected' : ''}`} key={index} title={`${index + 6}h: ${value}`}><div className="bar" style={{ height: `${Math.max(1, value / chartMax * 100)}%` }} /><span>{index + 6}h</span></div>)}</div></div>{showDetails && <div className="method-detail"><strong>Leitura responsável:</strong> a série do carro é uma faixa, porque faltam dados de uma cancela de entrada. A planilha individual soma todas as cancelas do campus e não foi usada como ocupação do rotativo. A amostra cobre apenas 17–21/08/2026.</div>}</div>
    </section>

    <section className="carpool-section" id="caronas"><div className="section-heading"><div><p className="eyebrow">02 · mobilidade compartilhada</p><h2>Chegue com mais gente.</h2></div><p className="section-note">Potencial agregado por bairro. O produto real precisa de login institucional e matching em tempo real.</p></div><div className="carpool-grid"><div className="carpool-list"><div className="list-head"><span>Onde você está?</span><select value={neighborhood} onChange={(event) => setNeighborhood(event.target.value)}>{neighborhoods.map((item) => <option key={item.name}>{item.name}</option>)}</select></div>{neighborhoods.map((item) => <button className={`neighborhood-row ${item.name === neighborhood ? 'selected' : ''}`} key={item.name} onClick={() => setNeighborhood(item.name)}><span className="neighborhood-dot" style={{ background: item.color }} /><span className="neighborhood-name">{item.name}</span><span className="neighborhood-meta">{item.students} alunos</span><strong>{item.groups}</strong><small>grupos</small></button>)}</div><div className="carpool-detail"><p className="eyebrow">Seu potencial de carona</p><h3>{selectedNeighborhood.name}</h3><div className="carpool-big"><strong>{selectedNeighborhood.groups}</strong><span>grupos de 3<br />possíveis pela manhã</span></div><div className="saving"><span>↓</span><div><strong>Até {Math.max(0, Math.round(selectedNeighborhood.cars - selectedNeighborhood.groups))} carros a menos</strong><p>Estimativa se cada grupo compartilhar um veículo.</p></div></div><button className="primary-button full" onClick={() => alert('Este protótipo demonstra o fluxo. O matching real será conectado ao login institucional na próxima fase.')}>Quero oferecer ou pedir carona <span>→</span></button></div></div></section>

    <section className="trust-section" id="metodo"><div className="trust-copy"><p className="eyebrow">03 · confiança antes da conveniência</p><h2>Uma previsão útil também sabe dizer “não sei”.</h2><p>O Vaga Certa não transforma um número incompleto em certeza. Ele combina o histórico do MBS32 com uma faixa conservadora, explicita o que falta e aponta para a decisão seguinte.</p><div className="trust-points"><div><span>01</span><strong>Histórico oficial</strong><p>5 dias de fluxo do rotativo, capacidade de 360 vagas.</p></div><div><span>02</span><strong>Incerteza visível</strong><p>Ocupação sai como piso–teto, não como falsa precisão.</p></div><div><span>03</span><strong>Plano B</strong><p>Carona e bicicleta entram quando o carro aperta.</p></div></div></div><div className="trust-quote"><span className="quote-mark">“</span><p>Não falta apenas vaga. Falta informação para decidir antes de chegar.</p><small>Vaga Certa · MVP de mobilidade PUC-Rio</small></div></section>
    <footer><div className="footer-brand"><span className="brand-mark">V</span><span>Vaga <em>Certa</em></span></div><p>Protótipo para o Impact Lab SIEng 2026 · PUC-Rio<br />Dados anonimizados cedidos pela DSI · Não é um serviço oficial</p><div className="footer-right"><span>Atualizado com base em 17–21 ago 2026</span><a href="#inicio">Voltar ao início ↑</a></div></footer>
  </main>;
}
